name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Run DotNet New 
      run: dotnet new web
    - name: Restore dependencies
      run: dotnet restore
    - name: Add & Commit dotnet files
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
    # - name: Build
    #   run: dotnet build --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
